resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - target:
      kind: ServiceAccount
      namespace: flux-system
      name: image-reflector-controller
      version: v1
    patch: |-
      - op: add
        path: /metadata/annotations/iam.gke.io~1gcp-service-account
        value: "image-reflector@prj-academeez.iam.gserviceaccount.com"
        