

apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: nginx
  namespace: nginx
spec:
  image: kubernetes.github.io/ingress-nginx/index.yaml  
  interval: 1h
  provider: generic
  