

apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: nginx
  namespace: nginx
spec:
  image: us-central1-docker.pkg.dev/prj-academeez/academeez-flux-course
  interval: 1h
  provider: generic