

apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: nginx
  namespace: nginx
spec:
  image: oci://chartproxy.container-registry.com/kubernetes.github.io/ingress-nginx
  interval: 1h
  provider: generic
  
  