# create a flux HelmChart for the nginx chart

apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:  
  chart:
    spec:
      chart: ingress-nginx
      version: 4.9.x
      sourceRef:
        kind: HelmRepository
        name: nginx
      interval: 5m
  interval: 10m
  timeout: 5m
  releaseName: nginx
  
