apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx
  namespace: nginx
spec:
  interval: 24h  
  url: oci://us-central1-docker.pkg.dev/prj-academeez/academeez-flux-course
  type: oci