apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx
  namespace: nginx
spec:
  interval: 24h
  type: oci
  url: oci://chartproxy.container-registry.com/kubernetes.github.io/ingress-nginx