# Auto-generated by `terragrunt catalog` from the `values.*` references in this unit/stack.
# Populate each `"TODO"` entry with a real value before running terragrunt.
#
# Required values come first. These are referenced directly by the unit or
# stack, so terragrunt will fail until you fill them in.
#
# Optional values come next, pre-populated with the defaults pulled from each
# reference's `try(...)` fallback. Edit any you want to override, or delete
# lines you're happy leaving at the fallback.


# === Optional (defaults from try() fallbacks) ===
conditional_bindings = []
mode                 = "authoritative"
