# Auto-generated by `terragrunt catalog` from the `values.*` references in this unit/stack.
# Populate each `"TODO"` entry with a real value before running terragrunt.
#
# Required values come first. These are referenced directly by the unit or
# stack, so terragrunt will fail until you fill them in.
#
# Optional values come next, pre-populated with the defaults pulled from each
# reference's `try(...)` fallback. Edit any you want to override, or delete
# lines you're happy leaving at the fallback.

# === Required ===
name = "academeez-k8s-flux-common"

# === Optional (defaults from try() fallbacks) ===
activate_api_identities                 = []
activate_apis                           = ["compute.googleapis.com"]
auto_create_network                     = false
bucket_force_destroy                    = false
bucket_labels                           = {}
bucket_location                         = "US"
bucket_name                             = ""
bucket_pap                              = "inherited"
bucket_project                          = ""
bucket_ula                              = true
bucket_versioning                       = false
budget_amount                           = 20
budget_alert_spend_basis                = "CURRENT_SPEND"
budget_alert_spent_percents             = [0.5, 0.7, 1]
budget_labels                           = {}
budget_monitoring_notification_channels = []
consumer_quotas                         = []
create_project_sa                       = true
default_network_tier                    = ""
default_service_account                 = "disable"
deletion_policy                         = "PREVENT"
disable_dependent_services              = true
disable_services_on_destroy             = true
domain                                  = ""
enable_shared_vpc_host_project          = false
essential_contacts                      = {}
grant_network_role                      = true
grant_services_security_admin_role      = false
group_name                              = ""
group_role                              = "roles/editor"
labels                                  = {}
language_tag                            = "en-US"
lien                                    = false
principal_set                           = ""
project_id                              = ""
project_sa_name                         = "project-service-account"
random_project_id                       = true
sa_role                                 = ""
shared_vpc_subnets                      = []
svpc_host_project_id                    = ""
tag_binding_values                      = []
universe_prefix                         = ""
usage_bucket_name                       = ""
usage_bucket_prefix                     = ""
vpc_service_control_attach_dry_run      = false
vpc_service_control_attach_enabled      = false
vpc_service_control_sleep_duration      = "5s"
