# Auto-generated by `terragrunt catalog` from the `values.*` references in this unit/stack.
# Populate each `"TODO"` entry with a real value before running terragrunt.
#
# Required values come first. These are referenced directly by the unit or
# stack, so terragrunt will fail until you fill them in.
#
# Optional values come next, pre-populated with the defaults pulled from each
# reference's `try(...)` fallback. Edit any you want to override, or delete
# lines you're happy leaving at the fallback.

# === Required ===
names = ["iam2"]

# === Optional (defaults from try() fallbacks) ===
all_folder_admins   = []
deletion_protection = false
folder_admin_roles  = ["roles/owner", "roles/resourcemanager.folderViewer", "roles/resourcemanager.projectCreator", "roles/compute.networkAdmin"]
per_folder_admins   = {}
prefix              = ""
set_roles           = false
