# Auto-generated by `terragrunt catalog` from the `values.*` references in this unit/stack.
# Populate each `"TODO"` entry with a real value before running terragrunt.
#
# Required values come first. These are referenced directly by the unit or
# stack, so terragrunt will fail until you fill them in.
#
# Optional values come next, pre-populated with the defaults pulled from each
# reference's `try(...)` fallback. Edit any you want to override, or delete
# lines you're happy leaving at the fallback.

# === Required ===
id = "k8s-flux-devops@academeez.com"

# === Optional (defaults from try() fallbacks) ===
description          = "k8s flux devops group"
display_name         = "k8s-flux-devops"
domain               = ""
initial_group_config = "EMPTY"
managers             = []
members              = ["k8s-flux@academeez.com"]
types                = ["default"]
