#
# Common configuration shared across environments.
# Generated by terragrunt scaffold — do not commit (see .gitignore).
#

locals {
  org_id         = "{{ .OrgId }}"
  common_project = "{{ .CommonProject }}"
  customer_id    = "{{ .CustomerId }}"
}
